[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rumqttc = "0.24"
bollard = "0.17"
influxdb2 = "0.5"
axum = "0.7"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls-tls", "smtp-transport", "builder"] }
futures-util = "0.3"
dashmap = "6"
influxdb2-derive = "0.1"
futures = "0.3"
chrono = "0.4.45"
